# Generated by Django 5.0 on 2023-12-29 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video_title', models.CharField(max_length=256, verbose_name='Put Your Video Title')),
                ('Upload_video', models.FileField(null=True, upload_to='videos', verbose_name='Upload Your Video')),
                ('slug', models.SlugField(max_length=264, unique=True)),
                ('Video_description', models.CharField(max_length=1000, verbose_name='Give a description :')),
                ('Upload_date', models.DateTimeField(auto_now_add=True)),
                ('Upload_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploader_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('Comment_date', models.DateTimeField(auto_now_add=True)),
                ('TheUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to=settings.AUTH_USER_MODEL)),
                ('TheVideo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_name', to='VideoSystem.videoupload')),
            ],
        ),
    ]
